# Generated by Django 3.1.4 on 2021-08-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=70)),
                ('course_description', models.CharField(max_length=200)),
                ('course_photo', models.ImageField(upload_to='')),
                ('course_link', models.CharField(max_length=200)),
            ],
        ),
    ]
