# Generated by Django 3.1.4 on 2021-08-03 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_category',
        ),
        migrations.AddField(
            model_name='video',
            name='video_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
    ]
